homepage: "https://dev.libra2.org"
language: rust
primary_contact: "gerardo@aptoslabs.com"
main_repo: "https://github.com/finalverse/libra2-core"
auto_ccs:
  - "oss-fuzz-notifications@aptoslabs.com"
  - "security@aptoslabs.com"
  - "andrea.cappa@aptoslabs.com"
  - "marco.ilardi@aptoslabs.com"
sanitizers:
  - none
fuzzing_engines:
  - libfuzzer
coverage_extra_args: -ignore-filename-regex=.*/rustc/.*