[package]
name = "FrameworkUsecases"
version = "0.0.0"

[dependencies]
Libra2Framework = { local = "../../../../../libra2-move/framework/libra2-framework" }
AptosToken = { local = "../../../../../libra2-move/framework/aptos-token" }
AptosTokenObjects = { local = "../../../../../libra2-move/framework/aptos-token-objects" }

# testing exchanging of constant address works as well.
[addresses]
publisher_address = "0xABCD"
