[package]
name = "AptosToken"
version = "1.0.0"

[addresses]
std = "0x1"
libra2_framework = "0x1"
aptos_token = "0x3"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
Libra2Framework = { local = "../libra2-framework"}
