[package]
name = "DataStructure"
version = "0.0.1"

[dependencies]
Libra2Stdlib = { git = "https://github.com/aptos-labs/libra2-framework.git", subdir = "libra2-stdlib", rev = "mainnet" }


[addresses]
std = "0x1"
