[package]
name = "test_case"
version = "1.0.0"
authors = []

[addresses]

[dev-addresses]

[dependencies.Libra2Framework]
git = "https://github.com/aptos-labs/libra2-framework.git"
rev = "mainnet"
subdir = "libra2-framework"

[dev-dependencies]
