{
 "title": "peer-monitoring-service",
 "tags": [ "aptos-core" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "metrics_source",
    "query": {
     "query": "label_values(node_process_start_time{}, metrics_source)"
    }
   },
   {
    "name": "chain_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\"},chain_name)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "kubernetes_pod_name",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"},kubernetes_pod_name)"
    }
   },
   {
    "name": "role",
    "query": {
     "query": "label_values(node_process_start_time{metrics_source=~\"$metrics_source\", chain_name=~\"$chain_name\", cluster=~\"$cluster\", namespace=~\"$namespace\"},role)"
    }
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Peer Monitoring Metadata", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Validator network: Ping latencies (seconds)",
   "type": "piechart",
   "description": "Histogram counts of the average ping latencies across peers on the Validator network (seconds).",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(peer_monitoring_client_average_ping_latencies_bucket{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", network_id=\"Validator\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator network: Distance from validators (hops)",
   "type": "piechart",
   "description": "Histogram counts of the distance from validators on the Validator network (hops).",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(peer_monitoring_client_distance_from_validators_bucket{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", network_id=\"Validator\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator network: Node uptime (hours)",
   "type": "piechart",
   "description": "Histogram counts of the node uptime on the Validator network (hours).",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(peer_monitoring_client_node_uptime_bucket{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", network_id=\"Validator\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Validator network: Number of connected peers",
   "type": "piechart",
   "description": "Histogram counts of the number of connected peers on the Validator network.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(peer_monitoring_client_num_connected_peers_bucket{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", network_id=\"Validator\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VFN network: Ping latencies (seconds)",
   "type": "piechart",
   "description": "Histogram counts of the average ping latencies across peers on the VFN network (seconds).",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(peer_monitoring_client_average_ping_latencies_bucket{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", network_id=\"vfn\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VFN network: Distance from validators (hops)",
   "type": "piechart",
   "description": "Histogram counts of the distance from validators on the VFN network (hops).",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(peer_monitoring_client_distance_from_validators_bucket{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", network_id=\"vfn\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VFN network: Node uptime (hours)",
   "type": "piechart",
   "description": "Histogram counts of the node uptime on the VFN network (hours).",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(peer_monitoring_client_node_uptime_bucket{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", network_id=\"vfn\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VFN network: Number of connected peers",
   "type": "piechart",
   "description": "Histogram counts of the number of connected peers on the VFN network.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(peer_monitoring_client_num_connected_peers_bucket{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", network_id=\"vfn\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Public network: Ping latencies (seconds)",
   "type": "piechart",
   "description": "Histogram counts of the average ping latencies across peers on the Public network (seconds).",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(peer_monitoring_client_average_ping_latencies_bucket{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", network_id=\"Public\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Public network: Distance from validators (hops)",
   "type": "piechart",
   "description": "Histogram counts of the distance from validators on the Public network (hops).",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(peer_monitoring_client_distance_from_validators_bucket{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", network_id=\"Public\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Public network: Node uptime (hours)",
   "type": "piechart",
   "description": "Histogram counts of the node uptime on the Public network (hours).",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(peer_monitoring_client_node_uptime_bucket{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", network_id=\"Public\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Public network: Number of connected peers",
   "type": "piechart",
   "description": "Histogram counts of the number of connected peers on the Public network.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (rate(peer_monitoring_client_num_connected_peers_bucket{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\", network_id=\"Public\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Monitoring Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Sent requests (per second)",
     "type": "timeseries",
     "description": "The sent data requests per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "rate(peer_monitoring_client_sent_requests{chain_name=~\"$chain_name\",  kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{network_id}}-{{request_types}}"
      }
     ]
    },
    {
     "title": "Successful responses (per second)",
     "type": "timeseries",
     "description": "The successful data responses per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "rate(peer_monitoring_client_success_responses{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{network_id}}-{{response_type}}"
      }
     ]
    },
    {
     "title": "In-flight requests",
     "type": "timeseries",
     "description": "The number of in-flight requests currently executing",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "peer_monitoring_client_in_flight_requests{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{request_type}}"
      }
     ]
    },
    {
     "title": "Error responses (per second)",
     "type": "timeseries",
     "description": "The error responses per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "expr": "rate(peer_monitoring_client_error_responses{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{network_id}}-{{response_type}}"
      }
     ]
    },
    {
     "title": "Request latencies (quantiles)",
     "type": "timeseries",
     "description": "The 0.99 quantile of all request latencies",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(peer_monitoring_client_request_latencies_bucket{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.70, sum(rate(peer_monitoring_client_request_latencies_bucket{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\"}[$__rate_interval])) by (le))",
       "legendFormat": "P70"
      }
     ]
    },
    {
     "title": "Average request latencies (per type)",
     "type": "timeseries",
     "description": "The average request latencies per data type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "peer_monitoring_client_request_latencies_sum{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}/peer_monitoring_client_request_latencies_count{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{network_id}}-{{request_type}}"
      }
     ]
    },
    {
     "title": "Ping latencies (quantiles)",
     "type": "timeseries",
     "description": "The 0.99 quantile of all ping latencies",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(peer_monitoring_client_request_latencies_bucket{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",request_type=\"latency_ping\"}[$__rate_interval])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.70, sum(rate(peer_monitoring_client_request_latencies_bucket{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",request_type=\"latency_ping\"}[$__rate_interval])) by (le))",
       "legendFormat": "P70"
      }
     ]
    },
    {
     "title": "Average ping latencies",
     "type": "timeseries",
     "description": "The average request latencies for ping requests.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "peer_monitoring_client_request_latencies_sum{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}/peer_monitoring_client_request_latencies_count{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\",request_type=\"latency_ping\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{network_id}}-{{request_type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Peer Monitoring Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests received (per second)",
     "type": "timeseries",
     "description": "The requests received per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "rate(libra2_peer_monitoring_service_server_requests_received{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{network_id}}-{{request_type}}"
      }
     ]
    },
    {
     "title": "Responses sent (per second)",
     "type": "timeseries",
     "description": "The responses sent per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "rate(libra2_peer_monitoring_service_server_responses_sent{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{network_id}}-{{response_type}}"
      }
     ]
    },
    {
     "title": "Request processing latencies (quantiles)",
     "type": "timeseries",
     "description": "The 0.99 quantile of all request processing latencies",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(libra2_peer_monitoring_service_server_request_latency_bucket{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",}[$__rate_interval])) by (le))",
       "legendFormat": "P99"
      },
      {
       "expr": "histogram_quantile(0.70, sum(rate(libra2_peer_monitoring_service_server_request_latency_bucket{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\",role=~\"$role\",}[$__rate_interval])) by (le))",
       "legendFormat": "P70"
      }
     ]
    },
    {
     "title": "Average request processing latencies (per type)",
     "type": "timeseries",
     "description": "The average request processing latencies per data type.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "libra2_peer_monitoring_service_server_request_latency_sum{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}/libra2_peer_monitoring_service_server_request_latency_count{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{network_id}}-{{request_type}}"
      }
     ]
    },
    {
     "title": "Pending network events (per second)",
     "type": "timeseries",
     "description": "The pending network events per second.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "targets": [
      {
       "expr": "rate(libra2_peer_monitoring_service_server_pending_network_events{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{network_id}}-{{state}}"
      }
     ]
    },
    {
     "title": "Storage errors (per second)",
     "type": "timeseries",
     "description": "The storage errors per second.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "targets": [
      {
       "expr": "rate(libra2_peer_monitoring_service_server_errors{chain_name=~\"$chain_name\", kubernetes_pod_name=~\"$kubernetes_pod_name\", role=~\"$role\"}[$interval])",
       "legendFormat": "{{kubernetes_pod_name}}-{{role}}-{{error_type}}"
      }
     ]
    }
   ]
  }
 ]
}