[package]
name = "NFTDAO"
version = "0.0.0"
upgrade_policy = "immutable"

[addresses]
dao_platform = "_"
libra2_framework = "0x1"

[dependencies]
Libra2Framework = { git = "https://github.com/aptos-labs/libra2-framework.git", subdir = "libra2-framework", rev = "mainnet" }
AptosToken = { git = "https://github.com/aptos-labs/libra2-framework.git", subdir = "aptos-token", rev = "mainnet" }
