[package]
name = "AA"
version = "0.0.0"

[addresses]
aa = "_"

[dependencies]
Libra2Framework = { local = "../../../framework/libra2-framework" }
AptosStdlib = { local = "../../../framework/aptos-stdlib" }
