[package]
name = 'ambassador'
version = '1.0.0'

# do not change to "_", concrete address needed for module-publish testing framework
[addresses]
ambassador = "0xCAFE"

[dependencies]
Libra2Framework = { git = "https://github.com/aptos-labs/libra2-framework.git", subdir = "libra2-framework", rev = "mainnet" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/libra2-framework.git", subdir = "aptos-token-objects", rev = "mainnet" }
