[package]
name = 'my_todo_list'
version = '1.0.0'
[dependencies.Libra2Framework]
git = 'https://github.com/aptos-labs/libra2-framework.git'
rev = 'main'
subdir = 'libra2-framework'
[addresses]
todolist_addr='_'